[release]
version = "0.1.3"
distributions = ["attest-cli"]

[compatibility]
library-version = "0.1.0"
store-version = "0.1.1"
action-version = "v1.0.3"
image = "ghcr.io/parth2412/attest@sha256:d5a370bff96f3dbe8eca341701060b73b915d9bade981e24a835f62362d2e2e1"
