[release]
version = "0.1.1"
distributions = ["attest-cli"]

[compatibility]
library-version = "0.1.0"
action-version = "v1.0.1"
image = "ghcr.io/parth2412/attest@sha256:0e5073cb4f2a9cc484f15aded43b7f0b8ac432a0a8b31fc401b7e361cd0509f3"
