"""Pure domain types and deterministic wire-format operations for attest."""

from attest_core.builder import build_statement
from attest_core.canonical import JsonValue, canonicalize
from attest_core.digest import build_changeset_record, compute_changeset_digest
from attest_core.errors import BuildError
from attest_core.identity import identity_pattern_matches, validate_identity_pattern
from attest_core.models import (
    AgentRef,
    Authorship,
    AuthorshipClaim,
    AuthorshipMode,
    AutomatedReview,
    ChangeSetEntry,
    ChangeSetInfo,
    ChangeSetRecord,
    ChangeSetStats,
    ChangeType,
    Check,
    CheckConclusion,
    ClaimScope,
    ClaimSource,
    ClaimSourceKind,
    Collection,
    CollectorRef,
    DigestSet,
    EnvironmentKind,
    EnvironmentRef,
    ModelRef,
    Predicate,
    Review,
    Reviewer,
    ReviewEvidence,
    ReviewState,
    ReviewVerdict,
    Statement,
    Subject,
)
from attest_core.path import decode_git_path, encode_git_path
from attest_core.schema import generate_json_schema, validate_statement_structure

__all__ = [
    "AgentRef",
    "Authorship",
    "AuthorshipClaim",
    "AuthorshipMode",
    "AutomatedReview",
    "BuildError",
    "ChangeSetEntry",
    "ChangeSetInfo",
    "ChangeSetRecord",
    "ChangeSetStats",
    "ChangeType",
    "Check",
    "CheckConclusion",
    "ClaimScope",
    "ClaimSource",
    "ClaimSourceKind",
    "Collection",
    "CollectorRef",
    "DigestSet",
    "EnvironmentKind",
    "EnvironmentRef",
    "JsonValue",
    "ModelRef",
    "Predicate",
    "Review",
    "ReviewEvidence",
    "ReviewState",
    "ReviewVerdict",
    "Reviewer",
    "Statement",
    "Subject",
    "build_changeset_record",
    "build_statement",
    "canonicalize",
    "compute_changeset_digest",
    "decode_git_path",
    "encode_git_path",
    "generate_json_schema",
    "identity_pattern_matches",
    "validate_identity_pattern",
    "validate_statement_structure",
]
